### PR TITLE
Remove observer pattern to please sonar.

### PR DESCRIPTION
**Pull request by ingokuba**
Well well well.... Observer pattern is deprecated :man_shrugging: I was bored

### CODE REVIEW

**Comment by ingokuba** [comment]
This also has the neat side effect that the json looks better. Attributes `changed` and `obs` will be removed.

**Comment by ingokuba** [comment]
Question: This is not backwards compatible - because of the json - should the version number be bumped up theoretically? @thisIsTheFoxe

**Comment by ingokuba** [comment]
Code coverage 100% :tada:

**Comment by thisIsTheFoxe** [comment]
perfect

**Pull request merged**
